In [1]:
import numpy as np
import os
import time
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input
from keras.applications.imagenet_utils import decode_predictions
from keras.layers import Dense, Activation, Flatten
from keras.layers import merge, Input
from keras.models import Model,Sequential
from keras.utils import np_utils
from sklearn import preprocessing
from keras.layers import *
from keras.models import *
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras.layers import Convolution2D, GlobalAveragePooling2D,Dropout
from keras.layers.recurrent import LSTM
import glob
from keras import optimizers
#from keras.applications.resnet50 import ResNet50

Using TensorFlow backend.


In [2]:
PATH = '../biswa_n_deba/FINAL_new1'
PATH1 = '../biswa_n_deba/FINAL_new1'
# Define data path
data_path = PATH + '/FINAL_TRAIN_MAG'
data_path1 = PATH1 + '/Train'
data_dir_list = os.listdir(data_path)
data_dir_list1 = os.listdir(data_path1)

In [3]:
data_dir_list.sort()
# data_dir_list.pop(8)
# data_dir_list.pop(8)
# data_dir_list.pop(3)
#data_dir_list.pop(0)
data_dir_list

['Archery-mag.csv',
 'BalanceBeam-mag.csv',
 'BaseballPitch-mag.csv',
 'BasketBall-mag.csv',
 'BasketBallDunk-mag.csv',
 'Biking-mag.csv',
 'Billiards-mag.csv',
 'Bowling-mag.csv',
 'BoxingPunchingBag-mag.csv',
 'BoxingSpeedBag-mag.csv',
 'BreastStroke-mag.csv',
 'CliffDiving-mag.csv',
 'CricketBowling-mag.csv',
 'Diving-mag.csv',
 'FieldHockeyPenalty-mag.csv',
 'FloorGymnastics-mag.csv',
 'FrisbeeCatch-mag.csv',
 'GolfSwing-mag.csv',
 'HighJump-mag.csv',
 'HorseRiding-mag.csv',
 'IceDancing-mag.csv',
 'JavelinThrow-mag.csv',
 'LongJump-mag.csv',
 'PoleVault-mag.csv',
 'Rafting-mag.csv',
 'RopeClimbing-mag.csv',
 'Shotput-mag.csv',
 'SkateBoarding-mag.csv',
 'Skiing-mag.csv',
 'Skijet-mag.csv',
 'SoccerPenalty-mag.csv',
 'Surfing-mag.csv',
 'TennisSwing-mag.csv']

In [4]:
data_dir_list1.sort()
#data_dir_list1.pop(0)
data_dir_list1

['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

In [5]:
__clip = '../biswa_n_deba/FINAL_new1/Train/'

actionClasses = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing'] 
actionClasses.sort()
len_class = []
clip1 = list()
clip = list()
for i in range(len(actionClasses)):
    clip1.append( __clip + actionClasses[i] + "/*.avi")
    clip.append(sorted(glob.glob(clip1[i])))
#print(clip[0])

for i in range(len(actionClasses)):
        len_class.append(len(clip[i] * 5))

In [6]:
len_class1 = len_class
len_class = np.array(len_class)
print(len_class)

[445 385 455 430 425 435 455 465 480 420 375 440 435 465 420 410 410 450
 400 495 480 405 425 450 390 395 445 400 430 375 430 420 500]


In [7]:
actionClasses

['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

In [8]:
i = 0
for files in data_dir_list:
    print(files)
    X = pd.read_csv(data_path + '/' + files)
    X = X.iloc[:,1:].values
    a = np.shape(X[0])
    print(a[0])
    len_class[i] = len_class[i] - a[0]
    i = i+1
i = 0

Archery-mag.csv
416
BalanceBeam-mag.csv
357
BaseballPitch-mag.csv
423
BasketBall-mag.csv
403
BasketBallDunk-mag.csv
368
Biking-mag.csv
419
Billiards-mag.csv
448
Bowling-mag.csv
420
BoxingPunchingBag-mag.csv
461
BoxingSpeedBag-mag.csv
405
BreastStroke-mag.csv
347
CliffDiving-mag.csv
394
CricketBowling-mag.csv
389
Diving-mag.csv
450
FieldHockeyPenalty-mag.csv
389
FloorGymnastics-mag.csv
386
FrisbeeCatch-mag.csv
372
GolfSwing-mag.csv
432
HighJump-mag.csv
354
HorseRiding-mag.csv
466
IceDancing-mag.csv
467
JavelinThrow-mag.csv
353
LongJump-mag.csv
389
PoleVault-mag.csv
398
Rafting-mag.csv
370
RopeClimbing-mag.csv
381
Shotput-mag.csv
407
SkateBoarding-mag.csv
358
Skiing-mag.csv
412
Skijet-mag.csv
362
SoccerPenalty-mag.csv
392
Surfing-mag.csv
407
TennisSwing-mag.csv
466


In [9]:
print(len_class)
z=0

[29 28 32 27 57 16  7 45 19 15 28 46 46 15 31 24 38 18 46 29 13 52 36 52
 20 14 38 42 18 13 38 13 34]


In [10]:
img_data_list = []
for files in data_dir_list:
    X = pd.read_csv(data_path + '/' + files)
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(0)
    X = X.iloc[:,1:].values
    Y = X[:,-1*len_class[z]:]
    #print(np.shape(Y))
    X = np.concatenate((X,Y),axis=1)
    print(np.shape(X))
    z = z+1
    print(files)
    for i in range(len(X[0])):
        col = X[:,i]
        #col = (col-np.amin(col))/(np.amax(col)-np.amin(col))
        col = np.reshape(col,(240,320))
        col = cv2.resize(col,(224,224),interpolation = cv2.INTER_CUBIC)
        col = np.repeat(col[:, :, np.newaxis], 3, axis=2)
        col = np.expand_dims(col, axis=0)
        col = preprocess_input(col)
        print('Input image shape:', col.shape)
        img_data_list.append(col)
        print(i)

(76800, 445)
Archery-mag.csv
('Input image shape:', (1, 224, 224, 3))
0
('Input image shape:', (1, 224, 224, 3))
1
('Input image shape:', (1, 224, 224, 3))
2
('Input image shape:', (1, 224, 224, 3))
3
('Input image shape:', (1, 224, 224, 3))
4
('Input image shape:', (1, 224, 224, 3))
5
('Input image shape:', (1, 224, 224, 3))
6
('Input image shape:', (1, 224, 224, 3))
7
('Input image shape:', (1, 224, 224, 3))
8
('Input image shape:', (1, 224, 224, 3))
9
('Input image shape:', (1, 224, 224, 3))
10
('Input image shape:', (1, 224, 224, 3))
11
('Input image shape:', (1, 224, 224, 3))
12
('Input image shape:', (1, 224, 224, 3))
13
('Input image shape:', (1, 224, 224, 3))
14
('Input image shape:', (1, 224, 224, 3))
15
('Input image shape:', (1, 224, 224, 3))
16
('Input image shape:', (1, 224, 224, 3))
17
('Input image shape:', (1, 224, 224, 3))
18
('Input image shape:', (1, 224, 224, 3))
19
('Input image shape:', (1, 224, 224, 3))
20
('Input image shape:', (1, 224, 224, 3))
21
('Input image

In [11]:
img_data = np.array(img_data_list)
print (img_data.shape)
img_data=np.rollaxis(img_data,1,0)
print (img_data.shape)
img_data=img_data[0]
print (img_data.shape) 

(14240, 1, 224, 224, 3)
(1, 14240, 224, 224, 3)
(14240, 224, 224, 3)


In [12]:
for i in range(len(len_class1)-1):
    len_class1[i+1] = len_class1[i+1] + len_class1[i]
print(len_class1)

[445, 830, 1285, 1715, 2140, 2575, 3030, 3495, 3975, 4395, 4770, 5210, 5645, 6110, 6530, 6940, 7350, 7800, 8200, 8695, 9175, 9580, 10005, 10455, 10845, 11240, 11685, 12085, 12515, 12890, 13320, 13740, 14240]


In [13]:
num_classes = len(actionClasses)
num_of_samples = img_data.shape[0]
labels = np.ones((num_of_samples),dtype='int64')
labels[0:len_class1[0]] = 0
print(len_class1[0])
i = 1
for i in range (1,num_classes):
    labels[len_class1[i-1] : len_class1[i]] = i
    print(len_class1[i-1],len_class1[i],i)
print(labels)

445
(445, 830, 1)
(830, 1285, 2)
(1285, 1715, 3)
(1715, 2140, 4)
(2140, 2575, 5)
(2575, 3030, 6)
(3030, 3495, 7)
(3495, 3975, 8)
(3975, 4395, 9)
(4395, 4770, 10)
(4770, 5210, 11)
(5210, 5645, 12)
(5645, 6110, 13)
(6110, 6530, 14)
(6530, 6940, 15)
(6940, 7350, 16)
(7350, 7800, 17)
(7800, 8200, 18)
(8200, 8695, 19)
(8695, 9175, 20)
(9175, 9580, 21)
(9580, 10005, 22)
(10005, 10455, 23)
(10455, 10845, 24)
(10845, 11240, 25)
(11240, 11685, 26)
(11685, 12085, 27)
(12085, 12515, 28)
(12515, 12890, 29)
(12890, 13320, 30)
(13320, 13740, 31)
(13740, 14240, 32)
[ 0  0  0 ... 32 32 32]


In [14]:
names = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

# convert class labels to on-hot encoding
Y = np_utils.to_categorical(labels, num_classes)

In [15]:
print(np.shape(Y))
print(Y)

(14240, 33)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [16]:
x_train = img_data

In [17]:
print(np.shape(x_train))

(14240, 224, 224, 3)


In [18]:
y_train = Y
print(np.shape(y_train))

(14240, 33)


In [22]:
PATH = '../biswa_n_deba/FINAL_new1'
PATH1 = '../biswa_n_deba/FINAL_new1'
# Define data path
data_path = PATH + '/FINAL_TEST_MAG'
data_path1 = PATH1 + '/Test'
data_dir_list = os.listdir(data_path)
data_dir_list1 = os.listdir(data_path1)

In [23]:
data_dir_list.sort()
#data_dir_list.pop(0)
data_dir_list
# data_dir_list.pop(8)
# data_dir_list.pop(3)
# data_dir_list.pop(7)
# data_dir_list

['Archery-mag.csv',
 'BalanceBeam-mag.csv',
 'BaseballPitch-mag.csv',
 'Basketball-mag.csv',
 'BasketballDunk-mag.csv',
 'Biking-mag.csv',
 'Billiards-mag.csv',
 'Bowling-mag.csv',
 'BoxingPunchingBag-mag.csv',
 'BoxingSpeedBag-mag.csv',
 'BreastStroke-mag.csv',
 'CliffDiving-mag.csv',
 'CricketBowling-mag.csv',
 'Diving-mag.csv',
 'FieldHockeyPenalty-mag.csv',
 'FloorGymnastics-mag.csv',
 'FrisbeeCatch-mag.csv',
 'GolfSwing-mag.csv',
 'HighJump-mag.csv',
 'HorseRiding-mag.csv',
 'IceDancing-mag.csv',
 'JavelinThrow-mag.csv',
 'LongJump-mag.csv',
 'PoleVault-mag.csv',
 'Rafting-mag.csv',
 'RopeClimbing-mag.csv',
 'Shotput-mag.csv',
 'SkateBoarding-mag.csv',
 'Skiing-mag.csv',
 'Skijet-mag.csv',
 'SoccerPenalty-mag.csv',
 'Surfing-mag.csv',
 'TennisSwing-mag.csv']

In [24]:
__clip = '../biswa_n_deba/FINAL_new1/Test/'

actionClasses = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing'] #35
actionClasses.sort()
len_class = []
clip1 = list()
clip = list()
for i in range(len(actionClasses)):
    clip1.append( __clip + actionClasses[i] + "/*.avi")
    clip.append(sorted(glob.glob(clip1[i])))
#print(clip[0])

for i in range(len(actionClasses)):
        len_class.append(len(clip[i] * 5))
        
len_class1 = len_class
len_class = np.array(len_class)
print(len_class)

[280 155 295 240 230 235 295 310 335 250 130 250 260 285 210 215 220 245
 215 325 290 180 230 295 165 200 255 200 245 125 255 210 330]


In [25]:
i = 0
for files in data_dir_list:
    print(files)
    X = pd.read_csv(data_path + '/' + files)
    X = X.iloc[:,1:].values
    a = np.shape(X[0])
    len_class[i] = len_class[i] - a[0]
    i = i+1
i = 0

print(len_class)

Archery-mag.csv
BalanceBeam-mag.csv
BaseballPitch-mag.csv
Basketball-mag.csv


/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (146) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


BasketballDunk-mag.csv
Biking-mag.csv
Billiards-mag.csv
Bowling-mag.csv
BoxingPunchingBag-mag.csv
BoxingSpeedBag-mag.csv
BreastStroke-mag.csv
CliffDiving-mag.csv
CricketBowling-mag.csv
Diving-mag.csv
FieldHockeyPenalty-mag.csv
FloorGymnastics-mag.csv
FrisbeeCatch-mag.csv
GolfSwing-mag.csv
HighJump-mag.csv
HorseRiding-mag.csv
IceDancing-mag.csv
JavelinThrow-mag.csv
LongJump-mag.csv
PoleVault-mag.csv
Rafting-mag.csv
RopeClimbing-mag.csv
Shotput-mag.csv
SkateBoarding-mag.csv
Skiing-mag.csv
Skijet-mag.csv
SoccerPenalty-mag.csv
Surfing-mag.csv
TennisSwing-mag.csv
[10 11 21 14 27  5  8 25 17  7 10 25 28 12 20  7 18  8 19 17 13 25 16 16
 15 12 26 18 12  5 23 10 21]


In [26]:
z=0
img_data_list = []
for files in data_dir_list:
    X = pd.read_csv(data_path + '/' + files)
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(0)
    X = X.iloc[:,1:].values
    Y = X[:,-1*len_class[z]:]
    #print(np.shape(Y))
    X = np.concatenate((X,Y),axis=1)
    print(np.shape(X))
    z = z+1
    print(files)
    for i in range(len(X[0])):
        col = X[:,i]
        #col = (col-np.amin(col))/(np.amax(col)-np.amin(col))
        col = np.reshape(col,(240,320))
        col = cv2.resize(col,(224,224),interpolation = cv2.INTER_CUBIC)
        col = np.repeat(col[:, :, np.newaxis], 3, axis=2)
        col = np.expand_dims(col, axis=0)
        col = preprocess_input(col)
        print('Input image shape:', col.shape)
        img_data_list.append(col)
        print(i)

(76800, 280)
Archery-mag.csv
('Input image shape:', (1, 224, 224, 3))
0
('Input image shape:', (1, 224, 224, 3))
1
('Input image shape:', (1, 224, 224, 3))
2
('Input image shape:', (1, 224, 224, 3))
3
('Input image shape:', (1, 224, 224, 3))
4
('Input image shape:', (1, 224, 224, 3))
5
('Input image shape:', (1, 224, 224, 3))
6
('Input image shape:', (1, 224, 224, 3))
7
('Input image shape:', (1, 224, 224, 3))
8
('Input image shape:', (1, 224, 224, 3))
9
('Input image shape:', (1, 224, 224, 3))
10
('Input image shape:', (1, 224, 224, 3))
11
('Input image shape:', (1, 224, 224, 3))
12
('Input image shape:', (1, 224, 224, 3))
13
('Input image shape:', (1, 224, 224, 3))
14
('Input image shape:', (1, 224, 224, 3))
15
('Input image shape:', (1, 224, 224, 3))
16
('Input image shape:', (1, 224, 224, 3))
17
('Input image shape:', (1, 224, 224, 3))
18
('Input image shape:', (1, 224, 224, 3))
19
('Input image shape:', (1, 224, 224, 3))
20
('Input image shape:', (1, 224, 224, 3))
21
('Input image

In [27]:
img_data = np.array(img_data_list)
print (img_data.shape)
img_data=np.rollaxis(img_data,1,0)
print (img_data.shape)
img_data=img_data[0]
print (img_data.shape) 

(7960, 1, 224, 224, 3)
(1, 7960, 224, 224, 3)
(7960, 224, 224, 3)


In [28]:
for i in range(len(len_class1)-1):
    len_class1[i+1] = len_class1[i+1] + len_class1[i]
print(len_class1)

[280, 435, 730, 970, 1200, 1435, 1730, 2040, 2375, 2625, 2755, 3005, 3265, 3550, 3760, 3975, 4195, 4440, 4655, 4980, 5270, 5450, 5680, 5975, 6140, 6340, 6595, 6795, 7040, 7165, 7420, 7630, 7960]


In [29]:
num_classes = len(actionClasses)
num_of_samples = img_data.shape[0]
labels = np.ones((num_of_samples),dtype='int64')
labels[0:len_class1[0]] = 0
print(len_class1[0])
i = 1
for i in range (1,num_classes):
    labels[len_class1[i-1] : len_class1[i]] = i
    print(len_class1[i-1],len_class1[i],i)
print(labels)

280
(280, 435, 1)
(435, 730, 2)
(730, 970, 3)
(970, 1200, 4)
(1200, 1435, 5)
(1435, 1730, 6)
(1730, 2040, 7)
(2040, 2375, 8)
(2375, 2625, 9)
(2625, 2755, 10)
(2755, 3005, 11)
(3005, 3265, 12)
(3265, 3550, 13)
(3550, 3760, 14)
(3760, 3975, 15)
(3975, 4195, 16)
(4195, 4440, 17)
(4440, 4655, 18)
(4655, 4980, 19)
(4980, 5270, 20)
(5270, 5450, 21)
(5450, 5680, 22)
(5680, 5975, 23)
(5975, 6140, 24)
(6140, 6340, 25)
(6340, 6595, 26)
(6595, 6795, 27)
(6795, 7040, 28)
(7040, 7165, 29)
(7165, 7420, 30)
(7420, 7630, 31)
(7630, 7960, 32)
[ 0  0  0 ... 32 32 32]


In [30]:
names = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

# convert class labels to on-hot encoding
Y = np_utils.to_categorical(labels, num_classes)

In [31]:
x_test = img_data
y_test = Y

In [32]:
# print(x_train)
# print(y_train)
# print(x_test)
# print(y_test)
print Y

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [33]:
image_input = Input(shape=(224, 224, 3))

In [34]:
model = VGG16(input_tensor=image_input, include_top=True,weights='imagenet')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [35]:
last_layer = model.get_layer('fc2').output
out = Dense(num_classes, activation='softmax', name='output')(last_layer)
custom_vgg_model = Model(image_input, out)
custom_vgg_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [36]:
custom_vgg_model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [37]:
for layer in custom_vgg_model.layers[:-1]:
    layer.trainable = False

In [38]:
custom_vgg_model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [39]:
custom_vgg_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [40]:
t=time.time()
#	t = now()
hist = custom_vgg_model.fit(x_train, y_train, batch_size=32, epochs=10, verbose=1, validation_data=(x_test, y_test))
print('Training time: %s' % (t - time.time()))
(loss, accuracy) = custom_vgg_model.evaluate(x_test, y_test, batch_size=10, verbose=1)

print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss,accuracy * 100))

Train on 14240 samples, validate on 7960 samples
Epoch 1/10
14240/14240 [==============================] - 59s 4ms/step - loss: 2.8922 - acc: 0.2118 - val_loss: 2.7119 - val_acc: 0.2803
Epoch 2/10
14240/14240 [==============================] - 55s 4ms/step - loss: 2.4028 - acc: 0.3231 - val_loss: 2.5456 - val_acc: 0.3123
Epoch 3/10
14240/14240 [==============================] - 55s 4ms/step - loss: 2.2024 - acc: 0.3753 - val_loss: 2.5461 - val_acc: 0.3180
Epoch 4/10
14240/14240 [==============================] - 55s 4ms/step - loss: 2.0611 - acc: 0.4072 - val_loss: 2.4566 - val_acc: 0.3544
Epoch 5/10
14240/14240 [==============================] - 55s 4ms/step - loss: 1.9422 - acc: 0.4404 - val_loss: 2.4393 - val_acc: 0.3690
Epoch 6/10
14240/14240 [==============================] - 55s 4ms/step - loss: 1.8577 - acc: 0.4558 - val_loss: 2.6488 - val_acc: 0.3153
Epoch 7/10
14240/14240 [==============================] - 55s 4ms/step - loss: 1.7857 - acc: 0.4766 - val_loss: 2.5700 - val_acc:

In [41]:
image_input = Input(shape=(224, 224, 3))

model = VGG16(input_tensor=image_input, include_top=True,weights='imagenet')

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [42]:
last_layer = model.get_layer('block5_pool').output
x= Flatten(name='flatten')(last_layer)
x = Dense(128, activation='relu', name='fc1')(x)
x = Dense(128, activation='relu', name='fc2')(x)
out = Dense(num_classes, activation='softmax', name='output')(x)
custom_vgg_model2 = Model(image_input, out)
custom_vgg_model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [43]:
# freeze all the layers except the dense layers
for layer in custom_vgg_model2.layers[:-3]:
    layer.trainable = False

custom_vgg_model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [44]:
custom_vgg_model2.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [45]:
t=time.time()
#	t = now()
hist = custom_vgg_model2.fit(x_train, y_train, batch_size=32, epochs=8, verbose=1, validation_data=(x_test, y_test))
print('Training time: %s' % (t - time.time()))
(loss, accuracy) = custom_vgg_model2.evaluate(x_test, y_test, batch_size=10, verbose=1)

print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss,accuracy * 100))

Train on 14240 samples, validate on 7960 samples
Epoch 1/8
14240/14240 [==============================] - 64s 4ms/step - loss: 2.7117 - acc: 0.2629 - val_loss: 2.4815 - val_acc: 0.3168
Epoch 2/8
14240/14240 [==============================] - 63s 4ms/step - loss: 1.7283 - acc: 0.5015 - val_loss: 2.2747 - val_acc: 0.3965
Epoch 3/8
14240/14240 [==============================] - 58s 4ms/step - loss: 1.2002 - acc: 0.6422 - val_loss: 2.4068 - val_acc: 0.4020
Epoch 4/8
14240/14240 [==============================] - 57s 4ms/step - loss: 0.8357 - acc: 0.7482 - val_loss: 2.6233 - val_acc: 0.4072
Epoch 5/8
14240/14240 [==============================] - 55s 4ms/step - loss: 0.5879 - acc: 0.8230 - val_loss: 2.8707 - val_acc: 0.4188
Epoch 6/8
14240/14240 [==============================] - 55s 4ms/step - loss: 0.4179 - acc: 0.8723 - val_loss: 3.3980 - val_acc: 0.4097
Epoch 7/8
14240/14240 [==============================] - 56s 4ms/step - loss: 0.3021 - acc: 0.9095 - val_loss: 3.5702 - val_acc: 0.4147

In [46]:
a = custom_vgg_model2.predict(x_train)

In [47]:
a[0]

array([9.97893274e-01, 3.87125001e-05, 1.98701673e-04, 2.07527250e-04,
       9.88570445e-13, 4.29724967e-09, 9.06901082e-11, 1.92583793e-05,
       2.90041537e-08, 2.70135584e-04, 1.21993656e-13, 4.94850028e-09,
       2.31518431e-08, 2.34460967e-04, 3.76997661e-04, 1.59604396e-11,
       3.52897551e-08, 3.50663431e-05, 3.71678254e-07, 1.67254748e-05,
       7.73625521e-12, 2.61455924e-09, 5.67057396e-05, 6.51755137e-04,
       3.08880092e-12, 4.23499706e-08, 8.96232564e-08, 3.45954709e-10,
       9.23066415e-11, 1.79358584e-09, 1.01661915e-10, 1.56121132e-07,
       7.82548870e-09], dtype=float32)

In [48]:
np.sum(a[2])

1.0

In [49]:
a = custom_vgg_model2.predict(x_train)
#c = model.predict(predictions)
b=np.shape(a)
#d=np.shape(c)
print(b)
print(np.shape(x_train))

(14240, 33)
(14240, 224, 224, 3)


In [51]:
a = a.reshape(2848,5,33)
print(np.shape(a))

(2848, 5, 33)


In [52]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [53]:
num_Frames = 5
num_classes = len(actionClasses)
LSTM_Model=Sequential()
LSTM_Model.add(LSTM(512, input_shape=(num_Frames,num_classes), return_sequences=False))
LSTM_Model.add(Activation('relu'))

LSTM_Model.add(Dense(256))
LSTM_Model.add(Activation('relu'))

LSTM_Model.add(Dense(num_classes))
LSTM_Model.add(Activation('softmax'))

LSTM_Model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
LSTM_Model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 512)               1118208   
_________________________________________________________________
activation_1 (Activation)    (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               131328    
_________________________________________________________________
activation_2 (Activation)    (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 33)                8481      
_________________________________________________________________
activation_3 (Activation)    (None, 33)                0         
Total params: 1,258,017
Trainable params: 1,258,017
Non-trainable params: 0
_________________________________________________________________


In [54]:
print(y_train)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [55]:
# print(y_train.shape)
# y_train = np_utils.to_categorical(y_train, num_classes)
# print(y_train.shape)
# print(y_test.shape)
# y_test =np_utils.to_categorical(y_test, num_classes)
# print(y_test.shape)

In [56]:
import pandas as pd
df = pd.DataFrame(np.array([[]]))
df

Empty DataFrame
Columns: []
Index: [0]

In [57]:
print(np.shape(y_train))
Y_train = []
for i in range(len(y_train)):
    if i % 5 == 0:
        Y_train.append(y_train[i])

print(np.shape(Y_train))
df = pd.DataFrame(Y_train)
Y_train = np.array(df)

(14240, 33)
(2848, 33)


In [58]:
Y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [59]:
df = pd.DataFrame(np.array([[]]))

print(np.shape(y_test))
Y_test = []
for i in range(len(y_test)):
    if i % 5 == 0:
        Y_test.append(y_test[i])

print(np.shape(Y_test))
df = pd.DataFrame(Y_test)
Y_test = np.array(df)

(7960, 33)
(1592, 33)


In [61]:
c = custom_vgg_model2.predict(x_test)
d= np.shape(c)
print(d)
c = c.reshape(1592,5,33)
print(np.shape(c))
#c = model.predict(predictions)

(7960, 33)
(1592, 5, 33)


In [62]:
Y_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [63]:
LSTM_Model.fit(a,Y_train,batch_size=32,epochs=10)

Epoch 1/10
2848/2848 [==============================] - 3s 1ms/step - loss: 1.0561 - acc: 0.9259
Epoch 2/10
2848/2848 [==============================] - 2s 754us/step - loss: 0.0228 - acc: 0.9947
Epoch 3/10
2848/2848 [==============================] - 2s 761us/step - loss: 0.0161 - acc: 0.9968
Epoch 4/10
2848/2848 [==============================] - 2s 760us/step - loss: 0.0131 - acc: 0.9968
Epoch 5/10
2848/2848 [==============================] - 2s 762us/step - loss: 0.0062 - acc: 0.9986
Epoch 6/10
2848/2848 [==============================] - 2s 762us/step - loss: 0.0047 - acc: 0.9989
Epoch 7/10
2848/2848 [==============================] - 2s 755us/step - loss: 0.0022 - acc: 0.9996
Epoch 8/10
2848/2848 [==============================] - 2s 757us/step - loss: 0.0074 - acc: 0.9986
Epoch 9/10
2848/2848 [==============================] - 2s 747us/step - loss: 0.0019 - acc: 0.9996
Epoch 10/10
2848/2848 [==============================] - 2s 752us/step - loss: 0.0114 - acc: 0.9972


In [64]:
numOfEpochs = 15
loss,acc = LSTM_Model.evaluate(c,Y_test,steps=numOfEpochs)

15/15 [==============================] - 0s 22ms/step


In [65]:
print('Test accuracy:', acc)
#LSTM_Model.save('./UCF_LSTM_MAG.h5')

('Test accuracy:', 0.55402010679245)


In [66]:
z = LSTM_Model.predict(c)
np.sum(z[0])

1.0

In [67]:
df = pd.DataFrame(np.array([[]]))
df_final = pd.DataFrame(np.array([[]]))

In [68]:
for i in range(len(z)):
    df = pd.DataFrame(z[i])
    df_final = pd.concat([df_final,df],axis  = 1)

In [69]:
df_final.to_csv("../biswa_n_deba/FINAL_new/MAG_LSTM.csv")

In [70]:
q = LSTM_Model.predict(c)

In [71]:
q = q[0]

In [72]:
r = np.amax(q)
for j in range(20):
    if(q[j]==r):
        q[j]=1
        print(j)
    else:
        q[j]=0


14


In [ ]:
q

In [ ]:
import requests
def email_alert():
    report = {}
    requests.post("https://maker.ifttt.com/trigger/alert_message/with/key/oXsatCBbGiCbaObQvSfqUSvRWKBApi766mxgs1306vE", data=report)  
if(j==10):
    email_alert()