In [1]:
import numpy as np
import os
import time
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input
from keras.applications.imagenet_utils import decode_predictions
from keras.layers import Dense, Activation, Flatten
from keras.layers import merge, Input
from keras.models import Model,Sequential
from keras.utils import np_utils
from sklearn import preprocessing
from keras.layers import *
from keras.models import *
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras.layers import Convolution2D, GlobalAveragePooling2D,Dropout
from keras.layers.recurrent import LSTM
import glob
from keras import optimizers
#from keras.applications.resnet50 import ResNet50

Using TensorFlow backend.


In [2]:
PATH = '../biswa_n_deba/FINAL_new1'
PATH1 = '../biswa_n_deba/FINAL_new1'
# Define data path
data_path = PATH + '/FINAL_TRAIN_ANG'
data_path1 = PATH1 + '/Train'
data_dir_list = os.listdir(data_path)
data_dir_list1 = os.listdir(data_path1)

In [3]:
data_dir_list.sort()
# data_dir_list.pop(8)
# data_dir_list.pop(8)
# data_dir_list.pop(3)
#data_dir_list.pop(0)
data_dir_list

['Archery-ang.csv',
 'BalanceBeam-ang.csv',
 'BaseballPitch-ang.csv',
 'BasketBall-ang.csv',
 'BasketBallDunk-ang.csv',
 'Biking-ang.csv',
 'Billiards-ang.csv',
 'Bowling-ang.csv',
 'BoxingPunchingBag-ang.csv',
 'BoxingSpeedBag-ang.csv',
 'BreastStroke-ang.csv',
 'CliffDiving-ang.csv',
 'CricketBowling-ang.csv',
 'Diving-ang.csv',
 'FieldHockeyPenalty-ang.csv',
 'FloorGymnastics-ang.csv',
 'FrisbeeCatch-ang.csv',
 'GolfSwing-ang.csv',
 'HighJump-ang.csv',
 'HorseRiding-ang.csv',
 'IceDancing-ang.csv',
 'JavelinThrow-ang.csv',
 'LongJump-ang.csv',
 'PoleVault-ang.csv',
 'Rafting-ang.csv',
 'RopeClimbing-ang.csv',
 'Shotput-ang.csv',
 'SkateBoarding-ang.csv',
 'Skiing-ang.csv',
 'Skijet-ang.csv',
 'SoccerPenalty-ang.csv',
 'Surfing-ang.csv',
 'TennisSwing-ang.csv']

In [4]:
data_dir_list1.sort()
#data_dir_list1.pop(0)
data_dir_list1

['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

In [5]:
__clip = '../biswa_n_deba/FINAL_new1/Train/'

actionClasses = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing'] #35
actionClasses.sort()
len_class = []
clip1 = list()
clip = list()
for i in range(len(actionClasses)):
    clip1.append( __clip + actionClasses[i] + "/*.avi")
    clip.append(sorted(glob.glob(clip1[i])))
#print(clip[0])

for i in range(len(actionClasses)):
        len_class.append(len(clip[i] * 5))

In [6]:
len_class1 = len_class
len_class = np.array(len_class)
print(len_class)

[445 385 455 430 425 435 455 465 480 420 375 440 435 465 420 410 410 450
 400 495 480 405 425 450 390 395 445 400 430 375 430 420 500]


In [7]:
actionClasses

['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

In [8]:
i = 0
for files in data_dir_list:
    print(files)
    X = pd.read_csv(data_path + '/' + files)
    X = X.iloc[:,1:].values
    a = np.shape(X[0])
    print(a[0])
    len_class[i] = len_class[i] - a[0]
    i = i+1
i = 0

Archery-ang.csv
416
BalanceBeam-ang.csv
357
BaseballPitch-ang.csv
423
BasketBall-ang.csv
403
BasketBallDunk-ang.csv
368
Biking-ang.csv
419
Billiards-ang.csv
448
Bowling-ang.csv
420
BoxingPunchingBag-ang.csv
461
BoxingSpeedBag-ang.csv
405
BreastStroke-ang.csv
347
CliffDiving-ang.csv
394
CricketBowling-ang.csv
389
Diving-ang.csv
450
FieldHockeyPenalty-ang.csv
389
FloorGymnastics-ang.csv
386
FrisbeeCatch-ang.csv
372
GolfSwing-ang.csv
432
HighJump-ang.csv
354
HorseRiding-ang.csv
466
IceDancing-ang.csv
467
JavelinThrow-ang.csv
353
LongJump-ang.csv
389
PoleVault-ang.csv
398
Rafting-ang.csv
370
RopeClimbing-ang.csv
381
Shotput-ang.csv
407
SkateBoarding-ang.csv
358
Skiing-ang.csv
412
Skijet-ang.csv
362
SoccerPenalty-ang.csv
392
Surfing-ang.csv
407
TennisSwing-ang.csv
466


In [9]:
print(len_class)
z=0

[29 28 32 27 57 16  7 45 19 15 28 46 46 15 31 24 38 18 46 29 13 52 36 52
 20 14 38 42 18 13 38 13 34]


In [10]:
img_data_list = []
for files in data_dir_list:
    X = pd.read_csv(data_path + '/' + files)
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(0)
    X = X.iloc[:,1:].values
    Y = X[:,-1*len_class[z]:]
    #print(np.shape(Y))
    X = np.concatenate((X,Y),axis=1)
    print(np.shape(X))
    z = z+1
    print(files)
    for i in range(len(X[0])):
        col = X[:,i]
        #col = (col-np.amin(col))/(np.amax(col)-np.amin(col))
        col = np.reshape(col,(240,320))
        col = cv2.resize(col,(224,224),interpolation = cv2.INTER_CUBIC)
        col = np.repeat(col[:, :, np.newaxis], 3, axis=2)
        col = np.expand_dims(col, axis=0)
        col = preprocess_input(col)
        print('Input image shape:', col.shape)
        img_data_list.append(col)
        print(i)

(76800, 445)
Archery-ang.csv
('Input image shape:', (1, 224, 224, 3))
0
('Input image shape:', (1, 224, 224, 3))
1
('Input image shape:', (1, 224, 224, 3))
2
('Input image shape:', (1, 224, 224, 3))
3
('Input image shape:', (1, 224, 224, 3))
4
('Input image shape:', (1, 224, 224, 3))
5
('Input image shape:', (1, 224, 224, 3))
6
('Input image shape:', (1, 224, 224, 3))
7
('Input image shape:', (1, 224, 224, 3))
8
('Input image shape:', (1, 224, 224, 3))
9
('Input image shape:', (1, 224, 224, 3))
10
('Input image shape:', (1, 224, 224, 3))
11
('Input image shape:', (1, 224, 224, 3))
12
('Input image shape:', (1, 224, 224, 3))
13
('Input image shape:', (1, 224, 224, 3))
14
('Input image shape:', (1, 224, 224, 3))
15
('Input image shape:', (1, 224, 224, 3))
16
('Input image shape:', (1, 224, 224, 3))
17
('Input image shape:', (1, 224, 224, 3))
18
('Input image shape:', (1, 224, 224, 3))
19
('Input image shape:', (1, 224, 224, 3))
20
('Input image shape:', (1, 224, 224, 3))
21
('Input image

In [11]:
img_data = np.array(img_data_list)
print (img_data.shape)
img_data=np.rollaxis(img_data,1,0)
print (img_data.shape)
img_data=img_data[0]
print (img_data.shape) 

(14240, 1, 224, 224, 3)
(1, 14240, 224, 224, 3)
(14240, 224, 224, 3)


In [12]:
for i in range(len(len_class1)-1):
    len_class1[i+1] = len_class1[i+1] + len_class1[i]
print(len_class1)

[445, 830, 1285, 1715, 2140, 2575, 3030, 3495, 3975, 4395, 4770, 5210, 5645, 6110, 6530, 6940, 7350, 7800, 8200, 8695, 9175, 9580, 10005, 10455, 10845, 11240, 11685, 12085, 12515, 12890, 13320, 13740, 14240]


In [13]:
num_classes = len(actionClasses)
num_of_samples = img_data.shape[0]
labels = np.ones((num_of_samples),dtype='int64')
labels[0:len_class1[0]] = 0
print(len_class1[0])
i = 1
for i in range (1,num_classes):
    labels[len_class1[i-1] : len_class1[i]] = i
    print(len_class1[i-1],len_class1[i],i)
print(labels)

445
(445, 830, 1)
(830, 1285, 2)
(1285, 1715, 3)
(1715, 2140, 4)
(2140, 2575, 5)
(2575, 3030, 6)
(3030, 3495, 7)
(3495, 3975, 8)
(3975, 4395, 9)
(4395, 4770, 10)
(4770, 5210, 11)
(5210, 5645, 12)
(5645, 6110, 13)
(6110, 6530, 14)
(6530, 6940, 15)
(6940, 7350, 16)
(7350, 7800, 17)
(7800, 8200, 18)
(8200, 8695, 19)
(8695, 9175, 20)
(9175, 9580, 21)
(9580, 10005, 22)
(10005, 10455, 23)
(10455, 10845, 24)
(10845, 11240, 25)
(11240, 11685, 26)
(11685, 12085, 27)
(12085, 12515, 28)
(12515, 12890, 29)
(12890, 13320, 30)
(13320, 13740, 31)
(13740, 14240, 32)
[ 0  0  0 ... 32 32 32]


In [15]:
names = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

# convert class labels to on-hot encoding
Y = np_utils.to_categorical(labels, num_classes)

In [16]:
print(np.shape(Y))
print(Y)

(14240, 33)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [17]:
x_train = img_data

In [18]:
print(np.shape(x_train))

(14240, 224, 224, 3)


In [19]:
y_train = Y
print(np.shape(y_train))

(14240, 33)


In [20]:
PATH = '../biswa_n_deba/FINAL_new1'
PATH1 = '../biswa_n_deba/FINAL_new1'
# Define data path
data_path = PATH + '/FINAL_TEST_ANG'
data_path1 = PATH1 + '/Test'
data_dir_list = os.listdir(data_path)
data_dir_list1 = os.listdir(data_path1)

In [21]:
data_dir_list.sort()
#data_dir_list.pop(0)
data_dir_list
# data_dir_list.pop(8)
# data_dir_list.pop(3)
# data_dir_list.pop(7)
# data_dir_list

['Archery-ang.csv',
 'BalanceBeam-ang.csv',
 'BaseballPitch-ang.csv',
 'Basketball-ang.csv',
 'BasketballDunk-ang.csv',
 'Biking-ang.csv',
 'Billiards-ang.csv',
 'Bowling-ang.csv',
 'BoxingPunchingBag-ang.csv',
 'BoxingSpeedBag-ang.csv',
 'BreastStroke-ang.csv',
 'CliffDiving-ang.csv',
 'CricketBowling-ang.csv',
 'Diving-ang.csv',
 'FieldHockeyPenalty-ang.csv',
 'FloorGymnastics-ang.csv',
 'FrisbeeCatch-ang.csv',
 'GolfSwing-ang.csv',
 'HighJump-ang.csv',
 'HorseRiding-ang.csv',
 'IceDancing-ang.csv',
 'JavelinThrow-ang.csv',
 'LongJump-ang.csv',
 'PoleVault-ang.csv',
 'Rafting-ang.csv',
 'RopeClimbing-ang.csv',
 'Shotput-ang.csv',
 'SkateBoarding-ang.csv',
 'Skiing-ang.csv',
 'Skijet-ang.csv',
 'SoccerPenalty-ang.csv',
 'Surfing-ang.csv',
 'TennisSwing-ang.csv']

In [22]:
__clip = '../biswa_n_deba/FINAL_new1/Test/'

actionClasses = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing'] #35
actionClasses.sort()
len_class = []
clip1 = list()
clip = list()
for i in range(len(actionClasses)):
    clip1.append( __clip + actionClasses[i] + "/*.avi")
    clip.append(sorted(glob.glob(clip1[i])))
#print(clip[0])

for i in range(len(actionClasses)):
        len_class.append(len(clip[i] * 5))
        
len_class1 = len_class
len_class = np.array(len_class)
print(len_class)

[280 155 295 240 230 235 295 310 335 250 130 250 260 285 210 215 220 245
 215 325 290 180 230 295 165 200 255 200 245 125 255 210 330]


In [23]:
i = 0
for files in data_dir_list:
    print(files)
    X = pd.read_csv(data_path + '/' + files)
    X = X.iloc[:,1:].values
    a = np.shape(X[0])
    len_class[i] = len_class[i] - a[0]
    i = i+1
i = 0

print(len_class)

Archery-ang.csv
BalanceBeam-ang.csv
BaseballPitch-ang.csv
Basketball-ang.csv
BasketballDunk-ang.csv
Biking-ang.csv
Billiards-ang.csv
Bowling-ang.csv
BoxingPunchingBag-ang.csv
BoxingSpeedBag-ang.csv
BreastStroke-ang.csv
CliffDiving-ang.csv
CricketBowling-ang.csv
Diving-ang.csv
FieldHockeyPenalty-ang.csv
FloorGymnastics-ang.csv
FrisbeeCatch-ang.csv
GolfSwing-ang.csv
HighJump-ang.csv
HorseRiding-ang.csv
IceDancing-ang.csv
JavelinThrow-ang.csv
LongJump-ang.csv
PoleVault-ang.csv
Rafting-ang.csv
RopeClimbing-ang.csv
Shotput-ang.csv
SkateBoarding-ang.csv
Skiing-ang.csv
Skijet-ang.csv
SoccerPenalty-ang.csv
Surfing-ang.csv
TennisSwing-ang.csv
[10 11 21 14 27  5  8 25 17  7 10 25 28 12 20  7 18  8 19 17 13 25 16 16
 15 12 26 18 12  5 23 10 21]


In [24]:
z=0
img_data_list = []
for files in data_dir_list:
    X = pd.read_csv(data_path + '/' + files)
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(0)
    X = X.iloc[:,1:].values
    Y = X[:,-1*len_class[z]:]
    #print(np.shape(Y))
    X = np.concatenate((X,Y),axis=1)
    print(np.shape(X))
    z = z+1
    print(files)
    for i in range(len(X[0])):
        col = X[:,i]
        #col = (col-np.amin(col))/(np.amax(col)-np.amin(col))
        col = np.reshape(col,(240,320))
        col = cv2.resize(col,(224,224),interpolation = cv2.INTER_CUBIC)
        col = np.repeat(col[:, :, np.newaxis], 3, axis=2)
        col = np.expand_dims(col, axis=0)
        col = preprocess_input(col)
        print('Input image shape:', col.shape)
        img_data_list.append(col)
        print(i)

(76800, 280)
Archery-ang.csv
('Input image shape:', (1, 224, 224, 3))
0
('Input image shape:', (1, 224, 224, 3))
1
('Input image shape:', (1, 224, 224, 3))
2
('Input image shape:', (1, 224, 224, 3))
3
('Input image shape:', (1, 224, 224, 3))
4
('Input image shape:', (1, 224, 224, 3))
5
('Input image shape:', (1, 224, 224, 3))
6
('Input image shape:', (1, 224, 224, 3))
7
('Input image shape:', (1, 224, 224, 3))
8
('Input image shape:', (1, 224, 224, 3))
9
('Input image shape:', (1, 224, 224, 3))
10
('Input image shape:', (1, 224, 224, 3))
11
('Input image shape:', (1, 224, 224, 3))
12
('Input image shape:', (1, 224, 224, 3))
13
('Input image shape:', (1, 224, 224, 3))
14
('Input image shape:', (1, 224, 224, 3))
15
('Input image shape:', (1, 224, 224, 3))
16
('Input image shape:', (1, 224, 224, 3))
17
('Input image shape:', (1, 224, 224, 3))
18
('Input image shape:', (1, 224, 224, 3))
19
('Input image shape:', (1, 224, 224, 3))
20
('Input image shape:', (1, 224, 224, 3))
21
('Input image

In [25]:
img_data = np.array(img_data_list)
print (img_data.shape)
img_data=np.rollaxis(img_data,1,0)
print (img_data.shape)
img_data=img_data[0]
print (img_data.shape) 

(7960, 1, 224, 224, 3)
(1, 7960, 224, 224, 3)
(7960, 224, 224, 3)


In [26]:
for i in range(len(len_class1)-1):
    len_class1[i+1] = len_class1[i+1] + len_class1[i]
print(len_class1)

[280, 435, 730, 970, 1200, 1435, 1730, 2040, 2375, 2625, 2755, 3005, 3265, 3550, 3760, 3975, 4195, 4440, 4655, 4980, 5270, 5450, 5680, 5975, 6140, 6340, 6595, 6795, 7040, 7165, 7420, 7630, 7960]


In [27]:
num_classes = len(actionClasses)
num_of_samples = img_data.shape[0]
labels = np.ones((num_of_samples),dtype='int64')
labels[0:len_class1[0]] = 0
print(len_class1[0])
i = 1
for i in range (1,num_classes):
    labels[len_class1[i-1] : len_class1[i]] = i
    print(len_class1[i-1],len_class1[i],i)
print(labels)

280
(280, 435, 1)
(435, 730, 2)
(730, 970, 3)
(970, 1200, 4)
(1200, 1435, 5)
(1435, 1730, 6)
(1730, 2040, 7)
(2040, 2375, 8)
(2375, 2625, 9)
(2625, 2755, 10)
(2755, 3005, 11)
(3005, 3265, 12)
(3265, 3550, 13)
(3550, 3760, 14)
(3760, 3975, 15)
(3975, 4195, 16)
(4195, 4440, 17)
(4440, 4655, 18)
(4655, 4980, 19)
(4980, 5270, 20)
(5270, 5450, 21)
(5450, 5680, 22)
(5680, 5975, 23)
(5975, 6140, 24)
(6140, 6340, 25)
(6340, 6595, 26)
(6595, 6795, 27)
(6795, 7040, 28)
(7040, 7165, 29)
(7165, 7420, 30)
(7420, 7630, 31)
(7630, 7960, 32)
[ 0  0  0 ... 32 32 32]


In [28]:
names = ['Archery',
 'BalanceBeam',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'Biking',
 'Billiards',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'CliffDiving',
 'CricketBowling',
 'Diving',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'GolfSwing',
 'HighJump',
 'HorseRiding',
 'IceDancing',
 'JavelinThrow',
 'LongJump',
 'PoleVault',
 'Rafting',
 'RopeClimbing',
 'Shotput',
 'SkateBoarding',
 'Skiing',
 'Skijet',
 'SoccerPenalty',
 'Surfing',
 'TennisSwing']

# convert class labels to on-hot encoding
Y = np_utils.to_categorical(labels, num_classes)

In [29]:
x_test = img_data
y_test = Y

In [30]:
# print(x_train)
# print(y_train)
# print(x_test)
# print(y_test)
print Y

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [31]:
image_input = Input(shape=(224, 224, 3))

In [32]:
model = VGG16(input_tensor=image_input, include_top=True,weights='imagenet')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [33]:
last_layer = model.get_layer('fc2').output
out = Dense(num_classes, activation='softmax', name='output')(last_layer)
custom_vgg_model = Model(image_input, out)
custom_vgg_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [34]:
custom_vgg_model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [35]:
for layer in custom_vgg_model.layers[:-1]:
    layer.trainable = False

In [36]:
custom_vgg_model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [37]:
custom_vgg_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [38]:
t=time.time()
#	t = now()
hist = custom_vgg_model.fit(x_train, y_train, batch_size=32, epochs=10, verbose=1, validation_data=(x_test, y_test))
print('Training time: %s' % (t - time.time()))
(loss, accuracy) = custom_vgg_model.evaluate(x_test, y_test, batch_size=10, verbose=1)

print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss,accuracy * 100))

Train on 14240 samples, validate on 7960 samples
Epoch 1/10
14240/14240 [==============================] - 51s 4ms/step - loss: 3.3601 - acc: 0.1178 - val_loss: 3.2431 - val_acc: 0.1268
Epoch 2/10
14240/14240 [==============================] - 48s 3ms/step - loss: 2.9990 - acc: 0.1915 - val_loss: 3.3617 - val_acc: 0.1455
Epoch 3/10
14240/14240 [==============================] - 49s 3ms/step - loss: 2.8359 - acc: 0.2264 - val_loss: 3.4002 - val_acc: 0.1436
Epoch 4/10
14240/14240 [==============================] - 49s 3ms/step - loss: 2.7396 - acc: 0.2409 - val_loss: 3.1552 - val_acc: 0.1761
Epoch 5/10
14240/14240 [==============================] - 49s 3ms/step - loss: 2.6502 - acc: 0.2624 - val_loss: 3.0525 - val_acc: 0.2094
Epoch 6/10
14240/14240 [==============================] - 49s 3ms/step - loss: 2.5747 - acc: 0.2796 - val_loss: 3.0890 - val_acc: 0.2227
Epoch 7/10
14240/14240 [==============================] - 49s 3ms/step - loss: 2.5070 - acc: 0.2978 - val_loss: 3.0724 - val_acc:

In [ ]:
image_input = Input(shape=(224, 224, 3))

model = VGG16(input_tensor=image_input, include_top=True,weights='imagenet')

model.summary()

In [ ]:
last_layer = model.get_layer('block5_pool').output
x= Flatten(name='flatten')(last_layer)
x = Dense(128, activation='relu', name='fc1')(x)
x = Dense(128, activation='relu', name='fc2')(x)
out = Dense(num_classes, activation='softmax', name='output')(x)
custom_vgg_model2 = Model(image_input, out)
custom_vgg_model2.summary()

In [ ]:
# freeze all the layers except the dense layers
for layer in custom_vgg_model2.layers[:-3]:
    layer.trainable = False

custom_vgg_model2.summary()

In [ ]:
custom_vgg_model2.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [ ]:
t=time.time()
#	t = now()
hist = custom_vgg_model2.fit(x_train, y_train, batch_size=32, epochs=8, verbose=1, validation_data=(x_test, y_test))
print('Training time: %s' % (t - time.time()))
(loss, accuracy) = custom_vgg_model2.evaluate(x_test, y_test, batch_size=10, verbose=1)

print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss,accuracy * 100))

In [ ]:
a = custom_vgg_model2.predict(x_train)

In [ ]:
a[0]

In [ ]:
np.sum(a[2])

In [ ]:
a = custom_vgg_model2.predict(x_train)
#c = model.predict(predictions)
b=np.shape(a)
#d=np.shape(c)
print(b)
print(np.shape(x_train))

In [ ]:
a = a.reshape(1738,5,20)
print(np.shape(a))

In [ ]:
num_Frames = 5
num_classes = len(actionClasses)
LSTM_Model=Sequential()
LSTM_Model.add(LSTM(512, input_shape=(num_Frames,num_classes), return_sequences=False))
LSTM_Model.add(Activation('relu'))

LSTM_Model.add(Dense(256))
LSTM_Model.add(Activation('relu'))

LSTM_Model.add(Dense(num_classes))
LSTM_Model.add(Activation('softmax'))

LSTM_Model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
LSTM_Model.summary()

In [ ]:
print(y_train)

In [ ]:
# print(y_train.shape)
# y_train = np_utils.to_categorical(y_train, num_classes)
# print(y_train.shape)
# print(y_test.shape)
# y_test =np_utils.to_categorical(y_test, num_classes)
# print(y_test.shape)

In [ ]:
import pandas as pd
df = pd.DataFrame(np.array([[]]))
df

In [ ]:
print(np.shape(y_train))
Y_train = []
for i in range(len(y_train)):
    if i % 5 == 0:
        Y_train.append(y_train[i])

print(np.shape(Y_train))
df = pd.DataFrame(Y_train)
Y_train = np.array(df)

In [ ]:
Y_train

In [ ]:
df = pd.DataFrame(np.array([[]]))

print(np.shape(y_test))
Y_test = []
for i in range(len(y_test)):
    if i % 5 == 0:
        Y_test.append(y_test[i])

print(np.shape(Y_test))
df = pd.DataFrame(Y_test)
Y_test = np.array(df)

In [ ]:
c = custom_vgg_model2.predict(x_test)
d= np.shape(c)
print(d)
c = c.reshape(994,5,20)
print(np.shape(c))
#c = model.predict(predictions)

In [ ]:
Y_test

In [ ]:
LSTM_Model.fit(a,Y_train,batch_size=32,epochs=10)

In [ ]:
numOfEpochs = 15
loss,acc = LSTM_Model.evaluate(c,Y_test,steps=numOfEpochs)

In [ ]:
print('Test accuracy:', acc)
LSTM_Model.save('./UCF_LSTM_ANG.h5')

In [ ]:
z = LSTM_Model.predict(c)
np.sum(z[0])

In [ ]:
df = pd.DataFrame(np.array([[]]))
df_final = pd.DataFrame(np.array([[]]))

In [ ]:
for i in range(len(z)):
    df = pd.DataFrame(z[i])
    df_final = pd.concat([df_final,df],axis  = 1)

In [ ]:
df_final.to_csv("../biswa_n_deba/FINAL_new/ANG_LSTM.csv")

In [ ]:
df = pd.DataFrame(np.array([[]]))
df_final = pd.DataFrame(np.array([[]]))

In [ ]:
for i in range(len(Y_test)):
    df = pd.DataFrame(Y_test[i])
    df_final = pd.concat([df_final,df],axis  = 1)

In [ ]:
df_final

In [ ]:
df_final.to_csv("../biswa_n_deba/FINAL_new/Y_LABEL.csv")